import { Quiz } from "./QuizCard";

export const fallbackQuizzes: Quiz[] = [
  {
    id: "mecanizado",
    title: "Mecanizado",
    description: "Próximamente: Evaluación sobre procesos de mecanizado.",
    icon: "🛠️",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Ingeniería Fundamental",
  },
  {
    id: "conformado",
    title: "Conformado",
    description: "Próximamente: Evaluación sobre procesos de conformado.",
    icon: "🔩",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Ingeniería Fundamental",
  },
  {
    id: "fundicion",
    title: "Fundición",
    description: "Próximamente: Evaluación sobre procesos de fundición.",
    icon: "🏭",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Ingeniería Fundamental",
  },
  {
    id: "calidad",
    title: "Calidad",
    description: "Próximamente: Evaluación sobre control de calidad.",
    icon: "📏",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Tecnologías Avanzadas",
  },
  {
    id: "materiales",
    title: "Materiales",
    description: "Próximamente: Evaluación sobre ciencia de materiales.",
    icon: "🧪",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Tecnologías Avanzadas",
  },
  {
    id: "automatizacion",
    title: "Automatización",
    description: "Próximamente: Evaluación sobre automatización industrial.",
    icon: "🤖",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Tecnologías Avanzadas",
  },
  {
    id: "diseno",
    title: "Diseño",
    description: "Próximamente: Evaluación sobre diseño industrial.",
    icon: "📐",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Tecnologías Avanzadas",
  },
  {
    id: "seguridad",
    title: "Seguridad",
    description: "Próximamente: Evaluación sobre seguridad industrial.",
    icon: "🦺",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Ciencias Aplicadas",
  },
  {
    id: "mantenimiento",
    title: "Mantenimiento",
    description: "Próximamente: Evaluación sobre mantenimiento industrial.",
    icon: "🔧",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Ciencias Aplicadas",
  },
  {
    id: "termodinamica",
    title: "Termodinámica",
    description: "Próximamente: Evaluación sobre termodinámica.",
    icon: "🔥",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Ciencias Aplicadas",
  },
  {
    id: "fluidos",
    title: "Fluidos",
    description: "Próximamente: Evaluación sobre dinámica de fluidos.",
    icon: "💧",
    color: "from-gray-400 to-gray-600",
    available: false,
    category: "Ciencias Aplicadas",
  },
];
